### PR TITLE
make script "toggle" on service start/stop

### PR DESCRIPTION
**Pull request by mainmachine**
Hey, nice project!

I made a similar but lighter version for my RX580, but I wanted to have defaults reinstated when the service is stopped, so I've modified your script to do this. Thought you might find it useful.

Cheers! :)

### CODE REVIEW

**Comment by dasunsrule32** [comment]
Hey, thanks for taking to time to submit this. I'll pull it down and test it over the weekend. I hope to keep adding to the project and provide more depth for sure. I'm glad it works on your rx580. I'll be renaming the scripts from vega-* to amd-* now that I have confirmation from others that it works with their devices.

**Comment by mainmachine** [comment]
Sorry, I wasn't clear - I haven't tested this on my RX580, I meant I have a similar script to yours that I use for the same purpose. Looking at your script, the Vega appears to have 4 memory power states, while the RX 580 only has three, so in addition to the vendor specific code blocks you're planning on, you'd have to add GPU or model specific allowances as well.

**Comment by dasunsrule32** [comment]
I'm sorry I haven't had time to look at his yet. I'll work on it as soon as I can. Thanks for your patience. :)

**Comment by dasunsrule32** [comment]
I've gone back and forth on this for a couple of weeks now. I've decided I'm going to rewrite the `vega-power-control` script. It's a bit of a kluge and needs to be fixed. I opened an issue [here](https://github.com/dasunsrule32/radeon-scripts/issues/17). Please comment and let me know your thoughts. Thanks for the submission. :)

**Pull request closed without merging**
